import subprocess
from Bio import AlignIO



datasetA = ['AACAATGACGTTTATGACTCATTTACTCGTAGGGG', 'TGATTGACGGTTATGGACTTATTTATCGTAGGGAT', 'AAGAATGGACGCTTATGGTCTCATTTATTCGAATCAGT', 'GAATTCAGGCTTATGGATTCATTTATTCGCAATT', 'TAAAATTGACGCCTATGGATTCATTTATTAGTACTATA', 'CTAAATGACGCTGATGGACCATTTATTCGTACGGA', 'AACAATGACACTTATGACTCATTTTTTCGTAGCTAG', 'CCATTGACGCTGATGGTCTCATTTATTCCTAGTCC', 'TGATTGACGCTTATGGACTCATTTATTCGAGGGAG', 'GAAATGGAGGCTTATAGACTCATTTATTAGTACTT', 'AAGGATTGACTCTTATGGACTCATTTATTCGCAGTCCGC', 'TGGACTTGACGTTTATGGCCTCATTAATTCGTATGAG', 'ATAAATTGAGCTTATGGACTCCTTTATTCGTAAACCC', 'AAGAATTAACGCTTATGGACTCCTTTATTCATAATCG', 'TTGAATTAACGCTTTGGACTCGTTTATTCGTATATG']

datasetB = ['AAATCGACGTTTATGGACTCATTAATTCGTATAGTC', 'AAAATTGACGCATATGGACCCATTTATTTGTAACTCTA', 'TAATTGAGCTTATGGACTCATTTATTCGTAACATC', 'AAATTACTCTTATGGAATCATTTATTCATACTACC', 'GCACATTGACGCTTATGGAATCATTTAGTCGTATCATT', 'CGATTGACGTTTATGGACTCATCTATTCGTAGCGGC', 'GGAATGACGCTTATGGACTGATTCATTCGTACCGGT', 'CCAATAGACGCTATGGACTGATTAATTCGTATTA', 'TCAATTGACGCTTTTGGACCCATTTATACGTATGG', 'AAAATGGACGCTTTGGACTCCTATATTCGTACAGTC', 'TGACTTGACGATTATGGCCTCATTTATTCTTAAGCA', 'GATAAATGACGCTTATGGACGCATTTACTCGTAGGT', 'GCATTGACGCTTGTGGACTCCTTAATTCGTAAATTT', 'CAAATTAACGCTTATGGACTCTTTTATTCGAAAG', 'TGAAATTAACGCTTATGGACTAATTTATCCGTAGTT', 'ATAATTGACGCATATGGACACATTTATTGGTAGGG', 'CCGTATTGACGCTTATTGACTCATTTATTGTAGGGTCG', 'TCGCATTGACGCTTTGGACCCATTTATACGTACTGG', 'AGTACTTGACGCTTATGACTCATTGATTCGTATGAC', 'GGATTGACGCTATGGACTAATTTATTCTAACGA', 'GATAATTGATGCTTATGAACTCATTTATTGGTATCTGT', 'GAAATGACCTTATGGACTGATTTATTCGTAGACCGC', 'GAGAATTGACGTTATGCACTCATTTAATCGTAGGATC', 'TAATTTGACGTTATGGACTCATTATTCGTAGCTG', 'GAATTTACGCTTATGGACTCATTTATTCGTACGAA', 'CATTTGACTCTTATCGACTCATTTTTTCGTACCCACG', 'TAGAATTGACGCTATGGACCATTTGTTCGTAATCA', 'CTATTGACGCTTATGGACTCCTTTATTCTTACGGAT', 'TTTAATTACGCGTATGGTCTCATTTATCGTAGCTCT', 'GTAAGTGACGTTATGGGCTCATTTATCGTAACGCAC', 'TAACTGACGCTTATGGACTCGTTATTCGTATGCTCC', 'AAGAACTGACGCTTATGGACTCGTTTTTTCGTAATTCT', 'CAATTGACGCTTCTGGAGTCATATATTCGTAGAGA', 'TAAATGACGCTATGGTCTCATTTATTCGCATGGGG', 'CCAATAGACGCTTATGCACTCATTTATTCGTAAATT']

'''with open("datasetA.fasta", "w") as file:
    file.write("\n".join(datasetA))'''

